---
#
# SPDX-License-Identifier: GPL-3.0-or-later

default:
  image: "archlinux:latest"

stages:
  - lint
  - build

shellcheck:
  stage: lint
  before_script:
    - pacman --noconfirm -Syu --needed make shellcheck
  script:
    - make lint

.build:
  stage: build
  before_script:
    - pacman -Syu --needed --noconfirm qemu-headless libisoburn
  script:
    - ./.gitlab/ci/build-host.sh
  after_script:
    - cp -- "output/${PROFILE}/job-metrics" metrics.txt
  artifacts:
    name: "output"
    paths:
      - "output/*/*"
    expire_in: 2d
    reports:
      metrics: metrics.txt

build_short:
  extends: .build
  parallel:
    matrix:
      # baseline does not support netboot with codesinging
      # https://gitlab.archlinux.org/archlinux/archiso/-/issues/132
      - PROFILE: baseline
        BUILDMODE:
          - bootstrap
      - PROFILE: releng
        BUILDMODE:
          - bootstrap

build_long:
  extends: .build
  tags:
    - fast-single-thread
  parallel:
    matrix:
      - PROFILE: baseline
        BUILDMODE:
          - iso
      - PROFILE: releng
        BUILDMODE:
          - iso
          - netboot
